### PR TITLE
Add publish_options. At first only the 'exclude_me'.

### PR DESCRIPTION
**Pull request by gajanak**
I added publishing options, and try to follow subscribe and call options the same way. 

Perhaps its usefull for someone. (Issue #92 )
Thanks for any hints, or improvements ...

### CODE REVIEW

**Comment by oberstet** [comment]
Nice! Thanks for contributing.

LGTM apart from 1 thing: options map should not go to the wire if it is empty (when the map doesn't hold at least a single key/value).

**Comment by oberstet** [comment]
So, in the impl. of overloads of session.publish that include an options parameter, we'd need a check for empty options (and not serialize an empty map).

Also: it's probably worth adding an overload that does not have an options parameter, as otherwise `options = wamp_publish_options()` will always (needlessly) construct an options map - performance optimization ..

**Comment by gajanak** [comment]
Macht es mehr Sinn die publish Methoden zusammenzufassen ? Eventuell sogar die Options auch per template parameter zu 'optimieren' ?

**Comment by oberstet** [comment]
I wouldn't do that.

> Btw: I figure you are a German speaker (me too), but could you pls post in English?

**Comment by gajanak** [comment]
The point, putting all publish together: Using template-pack would be fine. But i think, not all compiler supports it yet ;)

Would it be better to provide a single overload with 5 parameters ... and if someone want to use options , performace is perhaps , because of empty Parameter ? 


my first idea would be somthing like
'
message->set_field(3, topic);
    if (arguments.empty() && kw_arguments.empty())  
    {
        message->resize(4);
    } else {
        message->set_field(4, arguments);
        /* if kw_arguments is empty, remove it from message vector */
        if (kw_arguments.empty())  
        {
            message->resize(5);
        } else {
            message->set_field(5, kw_arguments);
        }     
    }
    
'
But for me , this isnt looking fine .... ;(  But wamp_message is only a vector ... resize down, shouldnt be a problem. But you are right ... it makes it slower.

(I hope, I get it explained a little bit, what i mean.) 
;)

If you say: looks fine, try it ... i would try to provide a pull request ... 

I know that publish_options ... is only needed for special,special solutions ... most time by not so good designed Use Cases.

**Comment by oberstet** [comment]
Actually, I should have looked more closely - which I now did;)

Because your PR as it stands keeps the API in coherence with what we already have for "session.call", eg https://github.com/crossbario/autobahn-cpp/blob/master/autobahn/wamp_session.hpp#L193

**Comment by oberstet** [comment]
So, thanks for your contribution!

**Comment by oberstet** [comment]
rgd GitHub formatting: you can have code block starting with 3 backticks plus language id like ```c++ and then end with 3 backtick again

**Pull request merged**
