### PR TITLE
wamp_session: set_exception on the correct future

### PR DESCRIPTION
**Pull request by jgriffiths**
Currently the start future is incorrectly signaled, probably cut'n'paste from the start method above.

### CODE REVIEW

**Comment by oberstet** [comment]
ah, right! thanks for contributing, I've enabled CI to run (only required on your 1st contribution) .. it runs into CI unfort. (not related to this PR):

```
Error: Unable to process command '::set-env name=CC::gcc-10' successfully.
Error: The `set-env` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
Error: Unable to process command '::set-env name=CXX::g++-10' successfully.
Error: The `set-env` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```

**Comment by oberstet** [comment]
so essentially, we need to change

https://github.com/crossbario/autobahn-cpp/blob/781686678d9606e77ad12cf79ba85aadf4e3d63d/.github/workflows/ci-linux.yaml#L58

according to

https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-environment-variable, as of

> Starting today runner version 2.273.5 will begin to warn you if you use the add-path or set-env commands. We are monitoring telemetry for the usage of these commands and plan to fully disable them in the future.

https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

**Comment by jgriffiths** [comment]
Hi @oberstet I've pushed an attempted fix for the CI, I will iterate should it prove insufficient, thanks.

**Comment by oberstet** [comment]
well, the environment vars are indeed needed;) so the syntax in the github job control needs a change:

`echo "{environment_variable_name}={value}" >> $GITHUB_ENV`

also, in doing so, we need to ensure that the job meta variable `matrix.version` is properly inserted into the value set for the env var ..

**Comment by jgriffiths** [comment]
The env vars have been set correctly via the `env:` section, the problem appears to be that using `gcc` rather than `g++` to link a c++executable doesn't include stdlib in the linker flags. As above, I'll iterate to get it working.

**Comment by jgriffiths** [comment]
OK, the non-conan builds are passing. conan seems to be broken by https://github.com/conan-io/conan/issues/8788

I'm out of time for fixing the other CI issues as I'm not familiar with conan and don't use windows.

**Comment by oberstet** [comment]
alright, I have found this https://blog.conan.io/2021/09/03/conancenter-declare-bintray-obsolete.html

let me see if I can add that to your PR and try ...

**Comment by oberstet** [comment]
that has worked https://github.com/crossbario/autobahn-cpp/pull/230

thanks for contributing!

**Comment by jgriffiths** [comment]
Thanks!

**Pull request merged**
