### PR TITLE
Feature/pattern registrations & subs

### LINKED ISSUE #46: Implement pattern-based subscriptions/registrations

### PR DESCRIPTION
**Pull request by DZabavchik**
Resolves #46, Answers #2

- invocation and event provide actual URI from message to callee/handler.
- Fixes for test projects (tested with crossbar 0.12.1)
- exclude UDS when not available (windows)

Logs from all examples attached as requested
[logs.zip](https://github.com/crossbario/autobahn-cpp/files/138535/logs.zip)

### CODE REVIEW

**Comment by DZabavchik** [comment]
wampcra log
```
Boost: 106000
starting io service
transport connected
responding to auth challenge: {"nonce": "YP8eFe1LD84FjqJg/3Od/LiuLqlT3bdRBHMjhfqKpCINzLo6lZ/OXP3bLZ1x8Upz", "authprovider": "static", "authid": "homer", "timestamp": "2016-02-19T19:07:22.637Z", "authrole": "user", "authmethod": "wampcra", "session": 4463981837606852}
signature: JvbMXm+ZRBcaxChLO0GjOLR8X6Ut31je0rQkq1wwfRg=
joined realm: 4463981837606852
left session (wamp.close.normal)
stopped session
stopped io service
 ```

**Comment by oberstet** [comment]
awesome! thanks! double thanks for testing with all included examples and crossbar=)

**Comment by DZabavchik** [comment]
so do we want dormant sample VS2015 projects along with crossbar.io config for windows?

**Comment by oberstet** [comment]
yes pls. 

I agree with Jakob that cmake should work for windows, and hence in principle would be enough, but windows devs likely expect VS project files I guess.

so yes if you have a PR with VS build stuff, I'd merge ..

**Pull request merged**
