### PR TITLE
VS2015 solution and example project files

### PR DESCRIPTION
**Pull request by DZabavchik**
Related to #95 #28 #2

### CODE REVIEW

**Comment by oberstet** [comment]
thanks!

**Comment by jpetso** [comment]
Wait, what changed that VS project files got merged now? Did I miss an argument why CMake doesn't work here?

**Comment by jpetso** [comment]
Oh I see, it was part of #101. Well... if you're willing to make that trade-off and it doesn't slow other contributions to the project more than it benefits, then your call :)

**Comment by oberstet** [comment]
yeah, the idea is: it's good to have a number of choices in build systems. and yes, that carries the risk of vuild systems getting out of sync. but currently, we just have a number of examples, so I think that is manageable ..

**Pull request merged**
